In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Beli.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['Demak' 44.0 72000.0]
 ['Grobogan' 27.0 48000.0]
 ['Semarang' 30.0 54000.0]
 ['Kendal' 38.0 61000.0]
 ['Ungaran' 40.0 nan]
 ['Salatiga' 35.0 58000.0]
 ['Grobogan' nan 52000.0]
 ['Demak' 48.0 79000.0]
 ['Semarang' 50.0 83000.0]
 ['Kendal' 37.0 67000.0]
 ['Salatiga' 45.0 nan]
 ['Ungaran' 34.0 44000.0]
 ['Demak' nan 34000.0]
 ['Kendal' 47.0 55000.0]
 ['Ungaran' 33.0 47000.0]
 ['Semarang' 46.0 75000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes'
 'No' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Demak' 44.0 72000.0]
 ['Grobogan' 27.0 48000.0]
 ['Semarang' 30.0 54000.0]
 ['Kendal' 38.0 61000.0]
 ['Ungaran' 40.0 59214.28571428572]
 ['Salatiga' 35.0 58000.0]
 ['Grobogan' 39.57142857142857 52000.0]
 ['Demak' 48.0 79000.0]
 ['Semarang' 50.0 83000.0]
 ['Kendal' 37.0 67000.0]
 ['Salatiga' 45.0 59214.28571428572]
 ['Ungaran' 34.0 44000.0]
 ['Demak' 39.57142857142857 34000.0]
 ['Kendal' 47.0 55000.0]
 ['Ungaran' 33.0 47000.0]
 ['Semarang' 46.0 75000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 40.0 59214.28571428572]
 [0.0 0.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 39.57142857142857 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 45.0 59214.28571428572]
 [0.0 0.0 0.0 0.0 0.0 1.0 34.0 44000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 39.57142857142857 34000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 47.0 55000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 33.0 47000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 46.0 75000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 1 1 0 0 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 0.0 39.57142857142857 52000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 45.0 59214.28571428572]
 [0.0 0.0 0.0 0.0 0.0 1.0 40.0 59214.28571428572]
 [0.0 1.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 33.0 47000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 46.0 75000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 39.57142857142857 34000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 34.0 44000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 35.0 58000.0]]


In [14]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 47.0 55000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 30.0 54000.0]]


In [15]:
print(y_train)

[0 0 1 1 0 0 1 1 0 1 1 1]


In [16]:
print(y_test)

[0 0 1 0]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 1.0 0.0 -0.44721359549995787 -0.447213595499958 -0.5773502691896258
  0.06364125395544139 -0.45575593151354044]
 [0.0 0.0 0.0 2.2360679774997894 -0.447213595499958 -0.5773502691896258
  0.9430476722488067 0.07435557423925394]
 [0.0 0.0 0.0 -0.44721359549995787 -0.447213595499958 1.7320508075688774
  0.13306807645228633 0.07435557423925394]
 [0.0 1.0 0.0 -0.44721359549995787 -0.447213595499958 -0.5773502691896258
  -1.9728788726186668 -0.7496791426240006]
 [0.0 0.0 0.0 -0.44721359549995787 -0.447213595499958 1.7320508075688774
  -1.0009033576628423 -0.8231599454016155]
 [1.0 0.0 0.0 -0.44721359549995787 -0.447213595499958 -0.5773502691896258
  0.7810517530895027 1.0138601240387601]
 [0.0 0.0 0.0 -0.44721359549995787 2.2360679774997902 -0.5773502691896258
  1.105043591408111 1.2343025323716053]
 [0.0 0.0 1.0 -0.44721359549995787 -0.447213595499958 -0.5773502691896258
  -0.35291968102562593 0.646456110150685]
 [0.0 0.0 0.0 -0.44721359549995787 2.2360679774997902 -0.5773502691896258


In [19]:
print(x_test)

[[0.0 0.0 1.0 -0.44721359549995787 -0.447213595499958 -0.5773502691896258
  -0.19092376186632184 0.20557129348499484]
 [0.0 0.0 1.0 -0.44721359549995787 -0.447213595499958 -0.5773502691896258
  1.2670395105674148 -0.23531352318069534]
 [1.0 0.0 0.0 -0.44721359549995787 -0.447213595499958 -0.5773502691896258
  1.429035429726719 1.5282257434820654]
 [0.0 0.0 0.0 -0.44721359549995787 2.2360679774997902 -0.5773502691896258
  -1.4868911151407544 -0.30879432595831036]]
